name: Download ANBIMA Reports

on:
  schedule:
    - cron: '0 11 * * 1'  # Roda toda segunda-feira às 08:00 BRT (11:00 UTC)
  workflow_dispatch:  # Permite execução manual

jobs:
  download-reports:
    runs-on: ubuntu-latest

    steps:
    # Checkout do repositório
    - name: Checkout code
      uses: actions/checkout@v3

    # Configura o Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Instala dependências do Python
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager

    # Instala o Chrome e o ChromeDriver usando uma ação específica
    - name: Setup Chrome and ChromeDriver
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: 'stable'  # Usa a versão estável mais recente
      id: setup-chrome

    # Verifica as versões instaladas
    - name: Verify Chrome and ChromeDriver installation
      run: |
        google-chrome --version
        chromedriver --version

    # Roda o script de download
    - name: Run download script
      run: python download_reports.py

    # (Opcional) Commit dos arquivos baixados no repositório
    - name: Commit downloaded files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Add downloaded ANBIMA reports for $(date +%Y-%m-%d)" || echo "No changes to commit"
        git push
