name: Download ANBIMA Relatórios e Upload no Google Drive

on:
  schedule:
    - cron: '0 11 * * 1'
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v4

    - name: Setup Chrome, Chromedriver e Selenium
      uses: nanasess/setup-chromedriver@v2

    - name: Instalar dependências Python
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install selenium gspread google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

    - name: Rodar o script Python (download e upload)
      env:
        GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
      run: |
        source venv/bin/activate
        python download_anbima.py
