name: Automatizar Download ANBIMA e Configuração do Chrome

on:
  schedule:
    - cron: '0 8 * * 1'  # Rodar toda segunda-feira às 08:00
  workflow_dispatch:  # Também pode ser acionado manualmente

jobs:
  setup:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      # Instala o Chrome 124 manualmente
      - name: Instalar Chrome 124
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip python3 python3-pip
          wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_124.0.6367.91-1_amd64.deb
          sudo apt install -y --allow-downgrades ./google-chrome-stable_124.0.6367.91-1_amd64.deb

      # Instala o ChromeDriver compatível
      - name: Baixar e instalar o ChromeDriver
        run: |
          # Obtém a versão do Chrome
          CHROME_VERSION=$(google-chrome --version | sed 's/Google Chrome //' | awk '{print $1}')
          CHROME_VERSION_MAJOR=$(echo $CHROME_VERSION | cut -d '.' -f 1)
          echo "Versão do Chrome: $CHROME_VERSION"
          echo "Versão principal do Chrome: $CHROME_VERSION_MAJOR"
          
          # Buscar o ChromeDriver correto
          DRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION_MAJOR})
          
          # Se não achar, pega o último disponível
          if [ -z "$DRIVER_VERSION" ]; then
            echo "Versão específica não encontrada. Baixando último ChromeDriver disponível."
            DRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          fi
          
          echo "Driver version: $DRIVER_VERSION"
          
          # Baixar e instalar
          wget -O chromedriver_linux64.zip "https://chromedriver.storage.googleapis.com/${DRIVER_VERSION}/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      # Instala as dependências para rodar o script Python
      - name: Instalar dependências Python
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install selenium google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      # Baixa os arquivos da ANBIMA (retentativa em caso de erro)
      - name: Baixar arquivos ANBIMA
        run: |
          mkdir -p ~/downloads/anbima
          
          # Tenta 3 vezes baixar os arquivos
          for i in {1..3}; do
            echo "Tentativa $i para baixar os arquivos..."
            python3 download_anbima.py && break || sleep 10
          done

      # Executa o script Python para processar os arquivos baixados
      - name: Processar arquivos ANBIMA
        run: |
          python3 process_anbima.py
