name: Download ANBIMA Relatórios

on:
  schedule:
    - cron: '0 11 * * 1'  # Segunda-feira 08:00 BRT (11h UTC)
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar Chrome e ChromeDriver
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: 'latest'
        chromedriver-version: 'latest'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install gspread google-auth google-auth-oauthlib google-auth-httplib2 selenium

    - name: Executar script
      run: python anbima_downloader.py

    - name: Fazer upload dos arquivos (opcional)
      uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
        name: anbima-reports
        path: downloads/
