name: Download Anbima Automático

on:
  schedule:
    - cron: '0 8 * * 1' # Toda segunda-feira às 08:00
  workflow_dispatch: # Permite executar manualmente também

jobs:
  download_anbima:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repositório
      uses: actions/checkout@v4

    - name: Instalar dependências
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip curl python3 python3-pip google-chrome-stable

    - name: Instalar Google Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Baixar e instalar ChromeDriver correto
      run: |
        # Obtenha a versão do Chrome
        CHROME_VERSION=$(google-chrome-stable --version | sed 's/Google Chrome //' | awk '{print $1}')
        CHROME_VERSION_MAJOR=$(echo $CHROME_VERSION | cut -d '.' -f 1)

        # Tente obter o ChromeDriver compatível
        DRIVER_VERSION=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION_MAJOR}")

        # Se não existir ChromeDriver para essa versão, pegue o último geral
        if [ -z "$DRIVER_VERSION" ]; then
          echo "Versão específica não encontrada. Baixando último ChromeDriver disponível."
          DRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
        fi

        # Baixe o ChromeDriver
        wget "https://chromedriver.storage.googleapis.com/${DRIVER_VERSION}/chromedriver_linux64.zip"

        # Extraia o arquivo
        unzip chromedriver_linux64.zip

        # Mova para o /usr/local/bin
        sudo mv chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Instalar dependências do Python
      run: |
        pip install -r requirements.txt

    - name: Rodar script de download
      run: |
        python3 download_anbima.py
