name: Download Anbima Automático

on:
  schedule:
    - cron: '0 8 * * 1'  # Segunda-feira às 08:00
  workflow_dispatch:

jobs:
  download_anbima:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v4

      - name: Instalar Chrome antigo compatível
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg unzip python3 python3-pip
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable=124.0.6367.91-1

      - name: Instalar ChromeDriver compatível
        uses: nanasess/setup-chromedriver@v2
        with:
          chrome-version: 124.0.6367.91

      - name: Instalar dependências Python
        run: |
          pip install -r requirements.txt

      - name: Rodar script de download
        run: |
          python3 download_anbima.py
