# .github/workflows/download.yml

name: Download ANBIMA Relatórios e Upload no Google Drive

on:
  schedule:
    - cron: '0 11 * * 1'  # Segunda-feira às 08:00 Brasília (11h UTC)
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v4

    - name: Instalar dependências Python e o Chrome
      run: |
        sudo apt update
        sudo apt install -y wget unzip gnupg2 python3-selenium
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt -f install -y

    - name: Instalar ambiente virtual e dependências do projeto
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install --no-cache-dir selenium gspread google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

    - name: Rodar o script Python (download e upload)
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
      run: |
        source venv/bin/activate
        python download_anbima.py
