name: Download ANBIMA Relatórios e Upload no Google Drive

on:
  schedule:
    - cron: '0 11 * * 1-5'  # Segunda a sexta às 08:00 BRT (11:00 UTC)
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v4

    - name: Setup Chrome e Chromedriver
      uses: nanasess/setup-chromedriver@v2
      with:
        chrome-version: 'stable'

    - name: Verificar versão do Chrome
      run: google-chrome --version

    - name: Configurar ambiente Python
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install selenium gspread google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

    - name: Rodar o script Python (download e upload)
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: |
        source venv/bin/activate
        python download_anbima.py
