name: Download ANBIMA Relatórios

on:
  schedule:
    - cron: '0 11 * * 1'  # Segunda-feira 08:00 Brasília (11h UTC)
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v4

    - name: Instalar Google Chrome
      run: |
        sudo apt update
        sudo apt install -y wget unzip gnupg2
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/google-chrome.gpg
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt update
        sudo apt install -y google-chrome-stable

    - name: Instalar ChromeDriver compatível
      run: |
        # Obtenha a versão do Chrome
        CHROME_VERSION=$(google-chrome-stable --version | sed 's/Google Chrome //' | awk '{print $1}')
        CHROME_VERSION_MAJOR=$(echo $CHROME_VERSION | cut -d '.' -f 1)

        # Encontre a versão mais recente do ChromeDriver compatível com a versão do Chrome
        DRIVER_VERSION=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION_MAJOR}")

        # Baixe o ChromeDriver compatível
        wget "https://chromedriver.storage.googleapis.com/${DRIVER_VERSION}/chromedriver_linux64.zip"

        # Extraia o arquivo
        unzip chromedriver_linux64.zip

        # Mova o arquivo do chromedriver para o diretório local
        sudo mv chromedriver /usr/local/bin/chromedriver

        # Torne o chromedriver executável
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Instalar dependências Python
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Executar o script Python para baixar os arquivos
      run: |
        source venv/bin/activate
        python download_script.py

    - name: Subir arquivos para o Google Drive
      run: |
        source venv/bin/activate
        python upload_to_drive.py
