name: Download Anbima Automático

on:
  schedule:
    - cron: '0 8 * * 1'
  workflow_dispatch:

jobs:
  download_anbima:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v4

      - name: Instalar Chrome 124 manualmente
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip python3 python3-pip
          wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_124.0.6367.91-1_amd64.deb
          sudo apt install -y ./google-chrome-stable_124.0.6367.91-1_amd64.deb

      - name: Instalar ChromeDriver compatível
        uses: nanasess/setup-chromedriver@v2
        with:
          chrome-version: 124.0.6367.91

      - name: Instalar dependências Python
        run: |
          pip install -r requirements.txt

      - name: Rodar script de download
        run: |
          python3 download_anbima.py
