name: Set up ChromeDriver

on:
  schedule:
    - cron: '0 8 * * 1'  # Executa toda segunda-feira às 08:00

jobs:
  setup-chromedriver:
    runs-on: ubuntu-latest

    steps:
    - name: Verificar versão do Chrome
      run: |
        CHROME_VERSION=$(google-chrome --version | sed 's/Google Chrome //' | awk '{print $1}')
        CHROME_VERSION_MAJOR=$(echo $CHROME_VERSION | cut -d '.' -f 1)
        echo "Versão do Chrome: $CHROME_VERSION"
        echo "Versão principal do Chrome: $CHROME_VERSION_MAJOR"

    - name: Buscar a versão correta do ChromeDriver
      run: |
        DRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION_MAJOR})
        if [ -z "$DRIVER_VERSION" ]; then
          echo "Versão específica não encontrada. Baixando o último ChromeDriver disponível."
          DRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
        fi
        echo "Driver version: $DRIVER_VERSION"
        if [ -z "$DRIVER_VERSION" ]; then
          echo "Erro: DRIVER_VERSION não foi atribuído corretamente."
          exit 1
        fi
        echo "URL para download do chromedriver: https://chromedriver.storage.googleapis.com/${DRIVER_VERSION}/chromedriver_linux64.zip"

    - name: Baixar e instalar o ChromeDriver
      run: |
        wget -O chromedriver_linux64.zip "https://chromedriver.storage.googleapis.com/${DRIVER_VERSION}/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver
